last_change = 2026-08-26T12:33:54.419862Z
addr = 0x151680
size = 0x3
name = "IGameSystem_OnServerPostEntityThink"

[header]
name = "IGameSystem_OnServerPostEntityThink"
addr = 0x151680

[header.args]
