last_change = 2026-08-26T12:33:54.419970Z
addr = 0x1edae0
size = 0x719
name = "CCSPlayerPawn_SprayPaint"
type = "long long"

[header]
name = "CCSPlayerPawn_SprayPaint"
addr = 0x1edae0
type = "long long"

[header.args]
