last_change = 2026-08-26T12:33:54.420064Z
addr = 0x3420e0
size = 0x1413
name = "CInferno_InfernoThink"
type = "long long"

[header]
name = "CInferno_InfernoThink"
addr = 0x3420e0
type = "long long"

[header.args]
