last_change = 2026-08-26T12:33:54.420128Z
addr = 0x526b60
size = 0xb7
name = "GetCSWeaponDataFromKey"
type = "long long"

[header]
name = "GetCSWeaponDataFromKey"
addr = 0x526b60
type = "long long"

[header.args]
