last_change = 2026-08-26T12:33:54.420261Z
addr = 0x61a150
size = 0x5
name = "CBaseModelEntity_ScriptSetRenderAlpha"

[header]
name = "CBaseModelEntity_ScriptSetRenderAlpha"
addr = 0x61a150

[header.args]
