last_change = 2026-08-26T12:33:54.420315Z
addr = 0x9e21e0
size = 0x1c7
name = "CBasePlayerWeapon_Shoot_Secondary"
type = "long long"

[header]
name = "CBasePlayerWeapon_Shoot_Secondary"
addr = 0x9e21e0
type = "long long"

[header.args]
