last_change = 2026-08-26T12:33:54.420433Z
addr = 0xaabbf0
size = 0x70b
name = "CCSPlayer_UseServices_BumpWeapon"
type = "long long"

[header]
name = "CCSPlayer_UseServices_BumpWeapon"
addr = 0xaabbf0
type = "long long"

[header.args]
