last_change = 2026-08-26T12:33:54.420449Z
addr = 0xacc5f0
size = 0x21e
name = "CTakeDamageInfo_GetWeaponName"
type = "const char *"

[header]
name = "CTakeDamageInfo_GetWeaponName"
addr = 0xacc5f0
type = "const char *"

[header.args]
