last_change = 2026-08-26T12:33:54.420438Z
addr = 0xac6940
size = 0x9e
name = "CBasePlayerPawn_RemovePlayerItem"
type = "void"

[header]
name = "CBasePlayerPawn_RemovePlayerItem"
addr = 0xac6940
type = "void"

[header.args]
