last_change = 2026-08-26T12:33:54.420442Z
addr = 0xac7200
size = 0x15c
name = "CCSPlayer_WeaponServices_DropWeapon"
type = "void"

[header]
name = "CCSPlayer_WeaponServices_DropWeapon"
addr = 0xac7200
type = "void"

[header.args]
