last_change = 2026-08-26T12:33:54.420472Z
addr = 0xb0d8a0
size = 0x61
name = "CBasePlayerPawn_GetEyePosition"
type = "long long"

[header]
name = "CBasePlayerPawn_GetEyePosition"
addr = 0xb0d8a0
type = "long long"

[header.args]
