last_change = 2026-08-26T12:33:54.420460Z
addr = 0xb08f30
size = 0x19e
name = "CCSPlayerController_Connect"
type = "long long"

[header]
name = "CCSPlayerController_Connect"
addr = 0xb08f30
type = "long long"

[header.args]
