last_change = 2026-08-26T12:33:54.420496Z
addr = 0xb26aa0
size = 0x5fe
name = "CBasePlayerController_ProcessUsercmds"
type = "long long"

[header]
name = "CBasePlayerController_ProcessUsercmds"
addr = 0xb26aa0
type = "long long"

[header.args]
