last_change = 2026-08-26T12:33:54.420538Z
addr = 0xb7b760
size = 0x2e4
name = "CEntitySaveRestoreBlockHandler_WriteSaveHeaders"
type = "long long"

[header]
name = "CEntitySaveRestoreBlockHandler_WriteSaveHeaders"
addr = 0xb7b760
type = "long long"

[header.args]
