last_change = 2026-08-26T12:33:54.420550Z
addr = 0xb7dad0
size = 0x49
name = "CSaveRestoreBlockSet_PostRestore"
type = "long long"

[header]
name = "CSaveRestoreBlockSet_PostRestore"
addr = 0xb7dad0
type = "long long"

[header.args]
