last_change = 2026-08-26T12:34:16.041984Z
addr = 0xb9c660
size = 0x154
name = "CGameEntitySystem_BuildResourceManifest_ManifestNameOrGroupName"
type = "long long"

[header]
name = "CGameEntitySystem_BuildResourceManifest_ManifestNameOrGroupName"
addr = 0xb9c660
type = "long long"

[header.args]
