last_change = 2026-08-26T12:33:54.420581Z
addr = 0xbb2c40
size = 0x29
name = "LegacyGameEventListener"
type = "long long"

[header]
name = "LegacyGameEventListener"
addr = 0xbb2c40
type = "long long"

[header.args]
