last_change = 2026-08-26T12:33:54.420597Z
addr = 0xbc2590
size = 0x3
name = "CEntitySystem_OnEntityParentChanged"
type = "void"

[header]
name = "CEntitySystem_OnEntityParentChanged"
addr = 0xbc2590
type = "void"

[header.args]
