last_change = 2026-08-26T12:34:16.839947Z
addr = 0xbc98c0
size = 0x215
name = "CSpawnGroupEntityFilterRegistrar_RegisterSpawnGroupEntityFilters"
type = "_UNKNOWN **"

[header]
name = "CSpawnGroupEntityFilterRegistrar_RegisterSpawnGroupEntityFilters"
addr = 0xbc98c0
type = "_UNKNOWN **"

[header.args]
