last_change = 2026-08-26T12:33:54.420833Z
addr = 0xcd7ef0
size = 0x22
name = "CEnvEntityIgniter_Precache"
type = "long long"

[header]
name = "CEnvEntityIgniter_Precache"
addr = 0xcd7ef0
type = "long long"

[header.args]
