last_change = 2026-08-26T12:33:54.420836Z
addr = 0xcfc290
size = 0x58
name = "CBreakable_DamageDecal"
type = "unsigned long long *"

[header]
name = "CBreakable_DamageDecal"
addr = 0xcfc290
type = "unsigned long long *"

[header.args]
