last_change = 2026-08-26T12:34:21.348528Z
addr = 0xd39300
size = 0x84f
name = "CSource2GameEntities_CheckTransmit"
type = "long long"

[header]
name = "CSource2GameEntities_CheckTransmit"
addr = 0xd39300
type = "long long"

[header.args]
