last_change = 2026-08-26T12:33:54.420917Z
addr = 0xd49290
size = 0x1d3
name = "CSource2GameClients_GetBugReportInfo"
type = "int"

[header]
name = "CSource2GameClients_GetBugReportInfo"
addr = 0xd49290
type = "int"

[header.args]
