last_change = 2026-08-26T12:33:54.421006Z
addr = 0x123da90
size = 0x4d9
name = "CEntitySystem_ctor"
type = "long long"

[header]
name = "CEntitySystem_ctor"
addr = 0x123da90
type = "long long"

[header.args]
