last_change = 2026-08-26T12:34:26.447573Z
addr = 0x124eb50
size = 0x21e
name = "CEntitySystem_RegisterEntityClass"
type = "long long"

[header]
name = "CEntitySystem_RegisterEntityClass"
addr = 0x124eb50
type = "long long"

[header.args]
