last_change = 2026-08-26T12:34:27.200338Z
addr = 0x12659f0
size = 0xc5
name = "CEntityInstance_ValidatePrivateScriptScope"
type = "void"

[header]
name = "CEntityInstance_ValidatePrivateScriptScope"
addr = 0x12659f0
type = "void"

[header.args]
