last_change = 2026-08-26T12:34:27.332527Z
addr = 0x1266930
size = 0xa
name = "CEntityInstance_NetworkUpdateState_thunk"
type = "long long"

[header]
name = "CEntityInstance_NetworkUpdateState_thunk"
addr = 0x1266930
type = "long long"

[header.args]
