last_change = 2026-08-26T12:34:27.111975Z
addr = 0x1264f80
size = 0x1c3
name = "CBaseEntity_ReloadPrivateScripts"
type = "void"

[header]
name = "CBaseEntity_ReloadPrivateScripts"
addr = 0x1264f80
type = "void"

[header.args]
